stages:
  - lint
  - ros_check

black:
  stage: lint
  image: python:3.8
  before_script:
    - pip install black
  script:
    # check number of python files, if 0, exit with success (true -> 0)
    - if [ $(git ls-files '*.py' | wc -l) -eq 0 ]; then exit 0; fi
    - black --check $(git ls-files '*.py')

pylint:
  stage: lint
  image: python:3.8
  before_script:
    - pip install pylint
  script:
    # check number of python files, if 0, exit with success (true -> 0)
    - if [ $(git ls-files '*.py' | wc -l) -eq 0 ]; then exit 0; fi
    - pylint $(git ls-files '*.py')

catkin_lint:
  stage: ros_check
  image: ros:noetic
  needs:
    - black
    - pylint
  allow_failure:
    exit_codes: 123 # Allow empty ROS_PACKAGES, but let it show as failed
  variables:
    # TODO: add only your own packages here
    ROS_PACKAGES: ""
  before_script:
    - apt update && apt install catkin-lint git libuvc-dev -y
  script:
    - if [[ -z "$ROS_PACKAGES" ]]; then exit 123; fi
    - mkdir -p catkin_ws/src
    - |
      for package in $ROS_PACKAGES; do
        cp -r $package catkin_ws/src/
      done
    - cd catkin_ws/src
    # TODO: add any other packages here that are required by your node.
    # - git clone https://github.com/arendjan/ridgeback.git
    # - git clone https://github.com/Slamtec/rplidar_ros.git
    # - git clone https://github.com/orbbec/ros_astra_camera.git

    - . /opt/ros/noetic/setup.sh
    - catkin_init_workspace
    - cd ..
    - rosdep init || true
    - rosdep update || true
    - rosdep install -y --from-paths src/ --ignore-src --rosdistro noetic
    - catkin_make
    - . devel/setup.sh

    # Run all tests before failing to test all packages
    - failure=false
    - |
      for package in $ROS_PACKAGES; do
        echo "Checking $package"
        catkin_lint --strict --explain --ignore uninstalled_target --ignore uninstalled_script --pkg $package || failure=true 
      done
    - if $failure; then
    - echo "Automated tests failed" >&2
    - exit 1
    - else
    - echo "Automated tests succeeded" >&2
    - exit 0
    - fi
